# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MCSLCode\MCSL2\Plugins\Server_Properties_Editor\singlePropertiesWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_singlePropertiesWidget(object):
    def setupUi(self, singlePropertiesWidget):
        singlePropertiesWidget.setObjectName("singlePropertiesWidget")
        singlePropertiesWidget.resize(644, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(singlePropertiesWidget.sizePolicy().hasHeightForWidth())
        singlePropertiesWidget.setSizePolicy(sizePolicy)
        singlePropertiesWidget.setMinimumSize(QtCore.QSize(644, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(singlePropertiesWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.propertyName = LineEdit(singlePropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyName.sizePolicy().hasHeightForWidth())
        self.propertyName.setSizePolicy(sizePolicy)
        self.propertyName.setMinimumSize(QtCore.QSize(185, 33))
        self.propertyName.setText("")
        self.propertyName.setReadOnly(True)
        self.propertyName.setObjectName("propertyName")
        self.horizontalLayout.addWidget(self.propertyName)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.propertyValue = LineEdit(singlePropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyValue.sizePolicy().hasHeightForWidth())
        self.propertyValue.setSizePolicy(sizePolicy)
        self.propertyValue.setMinimumSize(QtCore.QSize(185, 33))
        self.propertyValue.setObjectName("propertyValue")
        self.horizontalLayout.addWidget(self.propertyValue)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tip = BodyLabel(singlePropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip.sizePolicy().hasHeightForWidth())
        self.tip.setSizePolicy(sizePolicy)
        self.tip.setMinimumSize(QtCore.QSize(190, 0))
        self.tip.setWordWrap(True)
        self.tip.setObjectName("tip")
        self.horizontalLayout.addWidget(self.tip)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(singlePropertiesWidget)
        QtCore.QMetaObject.connectSlotsByName(singlePropertiesWidget)

    def retranslateUi(self, singlePropertiesWidget):
        _translate = QtCore.QCoreApplication.translate
        singlePropertiesWidget.setWindowTitle(_translate("singlePropertiesWidget", "Form"))
        self.propertyName.setPlaceholderText(_translate("singlePropertiesWidget", "配置项"))
        self.propertyValue.setPlaceholderText(_translate("singlePropertiesWidget", "值"))
        self.tip.setText(_translate("singlePropertiesWidget", "[注释]"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit
